# event_classifier/semantics/categories.py

"""
Diccionario de palabras clave para cada categoría de evento.
Estas palabras se usan en el módulo category_classifier.py
"""

CATEGORY_KEYWORDS = {
    "musica": [
        "concierto", "dj", "banda", "festival", "tour", "recital", "show musical",
        "live music", "album", "playlist", "gig", "set", "performance", "live show",
        "show en vivo", "evento musical", "musica en vivo", "party", "after party",
        "rave", "techno", "house", "trance", "edm", "rock", "pop", "hip hop", "rap",
        "reggaeton", "bachata", "salsa", "kpop", "jazz", "blues", "orquesta",
        "sinfonica", "classical", "symphony", "acustico", "cover", "tributo",
        "karaoke", "open mic", "session", "jam session", "ensayo", "instrumental",
        "guitarra", "bateria", "piano", "teclado", "bajo", "voz", "cantante",
        "compositor", "productor musical", "mezcla", "remix", "sample", "track",
        "single", "vinilo", "cd", "cassette", "mp3", "streaming", "soundcheck",
        "backstage", "crowd", "fan", "setlist", "tournee", "residencia",
        "musical theater", "opera", "fado", "flamenco", "cumbia", "merengue",
        "reggae", "country", "folk", "indie", "metal", "punk", "electronica",
        "ambient", "house progressive", "drum and bass", "trap", "lo-fi",
        "soundtrack", "bso", "score", "composición", "arreglos", "coros", "harmonía",
        "pop music", "concert", "pop show", "top hits", "chart music", "radio hits", "mainstream",
        "teen pop", "dance pop", "synth pop", "electropop", "pop festival", "pop live", "pop tour", "pop session",
        "rock music", "rock concert", "alternative", "hard rock",
        "grunge", "classic rock", "progressive rock", "garage rock", "rock festival", "rock tour",
        "psychedelic rock", "emo", "post punk", "soft rock", "rock live",
        "rap concert", "urban music", "rap battle", "freestyle", "rap session",
        "boom bap", "old school hip hop", "new school hip hop", "gangsta rap", "conscious rap", "underground hip hop",
        "rap festival", "cypher", "hip hop dance", "turntablism",
        "country music", "western", "bluegrass", "folk country", "americana", "country live",
        "honky tonk", "country festival", "country tour", "country singer", "country duo", "music"
    ],

    "artes_escenicas": [
        "teatro", "obra", "standup", "monologo", "ballet", "danza", "opera", "performance",
        "comedia", "cine", "film", "movie", "drama", "accion", "aventura", "terror",
        "suspenso", "thriller", "ciencia ficcion", "fantasia", "sci fi", "experimental",
        "improv", "sketch", "musical", "show en vivo", "dance show", "danza contemporanea",
        "danza urbana", "hip hop dance", "breakdance", "street dance", "freestyle dance",
        "teatro infantil", "teatro musical", "teatro de comedia", "teatro dramático",
        "performance art", "arte escénico", "danza clásica", "danza moderna", "danza folclórica",
        "danza latina", "tango", "salsa dance", "flamenco dance", "danza africana",
        "coreografía", "ensayo", "escenografía", "iluminación teatral", "vestuario",
        "maquillaje escénico", "dirección teatral", "actuación", "actor", "actriz", "bailarín",
        "bailarina", "coreógrafo", "director", "dramaturgia", "guion", "adaptación",
        "festival de teatro", "festival de cine", "proyección", "cortometraje", "largometraje",
        "documental", "animación", "cine experimental", "cine independiente", "cine de autor",
        "cine comercial", "cine mudo", "cine clásico", "cine contemporáneo", "escena", "acto",
        "entracte", "audiencia", "platea", "palco", "butaca", "clown", "circo", "malabarismo",
        "magia", "illusionismo", "teatro físico", "teatro gestual", "títeres", "marionetas",
        "puppetry", "performer", "showcase", "residencia artística", "laboratorio escénico",
        "urban dance", "dance battle", "popping", "locking", "krump", "house dance", "voguing",
        "urban showcase", "crew performance", "b-boying", "b-girling",
        "folklorico", "folclorica", "tradicional", "folk dance", "traditional dance", "cultural dance",
        "danzas tipicas", "danza regional", "danza autóctona", "festival folklórico", "ritual dance",
        "heritage dance", "ethnic dance", "fantasía", "science fiction", "fantasy", "sf", "space opera",
        "futuristic", "magic", "magical", "cyberpunk", "steampunk", "dystopia", "utopia",
        "time travel", "sci fi play", "fantasy show", "fantastic theatre",
        "ficcion", "cosplay", "anime", "fantastico", "inmersivo", "recorrido interactivo",
        "humor", "stand up", "comedy show", "humorístico", "parodia", "sátira", "slapstick",
        "comedia romántica", "comedia negra", "comediante", "cabaret", "comedia musical",
        "comic relief", "open mic", "show comico",
        "action", "adventure", "action movie", "thrill", "adrenalina", "espionaje",
        "superheroes", "stunts", "fight choreography", "martial arts", "blockbuster",
        "action show", "chase scene", "explosions", "epico", "heroe", "superheroe", "batalla",
        "dramatic play", "teatro serio", "drama contemporáneo", "drama clásico", "drama psicológico",
        "drama social", "drama experimental", "drama familiar", "drama romántico",
        "dramatic reading", "romantico", "romance", "melodrama", "obra dramatica", " performing & visual arts"
    ],
    "comunidad": [
        "conferencia", "charla", "panel", "meetup", "networking", "foro", "summit",
        "encuentro", "ponencia", "masterclass", "workshop", "talk", "seminar", "lecture",
        "exposicion", "expo", "showcase", "evento social", "encuentro cultural", "hackathon",
        "startup event", "business talk", "pitch", "entrepreneurship", "cultural event",
        "feria", "festival cultural", "meet and greet", "social gathering",
        "congreso", "simposio", "mesa redonda", "roundtable", "brainstorming session",
        "retreat", "team building", "networking dinner", "afterwork", "coffee chat",
        "community meetup", "volunteering event", "charity event", "fundraiser",
        "panel discussion", "fireside chat", "talk show", "interactive workshop",
        "bootcamp", "training session", "learning circle", "innovation lab",
        "co-working session", "pitch competition", "demo day", "startup fair",
        "career fair", "job fair", "cultural exchange", "cultural night",
        "film screening", "book reading", "art exhibition", "gallery opening",
        "music meetup", "creative workshop", "design thinking session",
        "hack day", "tech meetup", "science fair", "educational seminar",
        "public lecture", "community forum", "youth summit", "mentor session",
        "panel debate", "storytelling session", "networking brunch", "club meeting",
        "roundtable discussion", "industry talk", "open house", "town hall meeting",
        "discussion group", "interest group", "community gathering", "local event",
        "ventas", "funnel", "marketing", "estrategia", "comercial", "negocios",
        "empresa", "emprendimiento", "startup", "negociacion", "crm", "ventas b2b",
        "ventas b2c", "growth", "lead generation", "conversion rate", "business", "deal",
        "meeting", "strategy session", "empresarios", "charla de negocios", "gala",
        "industria", "evento empresarial", "liderazgo", "finanzas", "inversión",
        "capital de riesgo", "panel de inversionistas", "cumbre empresarial",
        "reunión ejecutiva", "lanzamiento de producto", "taller corporativo",
        "retiro corporativo", "empresarial", "negocio",
        "ciencia", "tecnología", "investigación", "innovación", "charla tecnológica",
        "feria de ciencias", "evento STEM", "taller científico", "laboratorio de innovación",
        "presentación de investigación", "conferencia científica", "expo tecnológica",
        "reunión de tecnología", "tour de laboratorio", "innovacion", "robotica", "ia",
        "inteligencia artificial", "astronomia", "divulgacion cientifica", "tech workshop",
        "política", "gobierno", "política pública", "debate", "asamblea ciudadana",
        "elecciones", "compromiso cívico", "mitin político", "sesión parlamentaria",
        "reunión legislativa", "foro político", "taller de políticas públicas",
        "seminario político", "campaña", "evento cívico",
        "cultura", "arte", "historia", "museo", "galería", "patrimonio", "evento cultural",
        "feria de arte", "tour cultural", "noche cultural", "taller creativo",
        "cuenta cuentos", "intercambio cultural", "evento folclórico", "feria de artesanía",
        "charla de artistas", "tradicion", "colectivo", "mercado creativo", "travel & outdoor", "food & drink", "religion & spirituality",
        "business & professional", "science & technology", "community & culture", " government & politics"
    ],

    "deportes": [
        "partido", "vs", "liga", "torneo", "campeonato", "competencia", "match", "game",
        "race", "carrera", "futbol", "soccer", "football", "nba", "basketball", "tenis",
        "tennis", "beisbol", "baseball", "boxeo", "boxing", "mma", "karate", "taekwondo",
        "lucha libre", "american football", "gridiron", "nascar", "formula 1", "rally", "motorsport",
        "grand prix", "home run", "knockout", "championship", "tournament", "athletics", "training", "sports & fitness"
    ],

    "actividad_fisica": [
        "running", "correr", "caminar", "hiking", "trail", "maraton", "clase fitness", "entrenamiento",
        "bootcamp", "crossfit", "hiit", "exercise", "workout", "gym class", "cycling", "bike ride",
        "jogging", "stretch", "yoga", "pilates", "dance workout", "active", "outdoor activity",
        "gentle hike", "moderate run", "intense workout", "high intensity", "fitness session", "health & wellness"
    ]
}
